version: 2

.build-steps: &build-steps
  docker:
    - image: conanio/gcc8:latest
  steps:
    - checkout
    - run:
        name: Install
        command: |
          sudo apt-get update
          sudo apt-get install -y firefox wget
          pushd /tmp
          wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
          tar xzf geckodriver-v0.24.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/bin/geckodriver
          popd
          pip install -r requirements.txt
    - run:
        name: Collect statistics
        no_output_timeout: 1200
        command: |
          python conan-statistics.py
        environment:
          CONAN_TOTAL_PAGES: "8"

jobs:
  page-1:
    environment:
      - CONAN_CURRENT_PAGE: "1"
    <<: *build-steps

  page-2:
    environment:
      - CONAN_CURRENT_PAGE: "2"
    <<: *build-steps

  page-3:
    environment:
      - CONAN_CURRENT_PAGE: "3"
    <<: *build-steps

  page-4:
    environment:
      - CONAN_CURRENT_PAGE: "4"
    <<: *build-steps

  page-5:
    environment:
      - CONAN_CURRENT_PAGE: "5"
    <<: *build-steps

  page-6:
    environment:
      - CONAN_CURRENT_PAGE: "6"
    <<: *build-steps

  page-7:
    environment:
      - CONAN_CURRENT_PAGE: "7"
    <<: *build-steps

  page-8:
    environment:
      - CONAN_CURRENT_PAGE: "8"
    <<: *build-steps
    
  merge-all-pages:
    docker:
      - image: conanio/gcc8:latest
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get update
            sudo apt-get install -y firefox wget
            pushd /tmp
            wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
            tar xzf geckodriver-v0.24.0-linux64.tar.gz
            chmod +x geckodriver
            sudo mv geckodriver /usr/bin/geckodriver
            popd
            pip install -r requirements.txt
      - run:
          name: Collect Total statistics
          no_output_timeout: 1200
          command: |
            python collect-results.py


workflows:
  version: 2
  build_and_test:
    jobs:
      - page-1
      - page-2
      - page-3
      - page-4
      - page-5
      - page-6
      - page-7
      - page-8
      - merge-all-pages:
          requires:
            - page-1
            - page-2
            - page-3
            - page-4
            - page-5
            - page-6
            - page-7
            - page-8
