version: 2

jobs:
  collect-data:
    docker:
      - image: conanio/gcc8:latest
    steps:
      - checkout
      - run:
          name: Install
          command: |
            pip install -r requirements.txt
      - run:
          name: Collect statistics
          no_output_timeout: 1200
          command: |
            python conan-get-ip.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - collect-data
